# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Global workflow envs
# env:
#   ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/x.x.x
#   ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/x.x.x

# TODO: Avoid brutally editing/setting ndk.dir in local.properties

jobs:
  build-android:

    runs-on: ubuntu-24.04 #Â https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md

    # Local job envs

    steps:

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Setup JDK 19
      uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
      with:
        java-version: 19
        distribution: temurin
        cache: 'gradle'

#       yarn cache
#       node_modules cache

    - name: Install deps and setup
      run: yarn && yarn setup

    - name: npx react-native info
      run: npx react-native info

#     - name: Build application Debug APK with Gradle
#       uses: gradle/gradle-build-action@v2.4.2
#       with:
#         arguments: assembleDebug
#         build-root-directory: android

#     Avoid release poisoned cache problems
#     Preserve hosted agent free disk space
#     - name: Delete Android build pre-computed outputs
#       uses: gradle/gradle-build-action@v2.4.2
#       with:
#         arguments: clean
#         build-root-directory: android

    - name: Build application Release APK with Gradle
      uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629 # v2.4.2
      with:
        arguments: assembleRelease
        build-root-directory: android

#     - name: Build project Make-based (not CMake)
#       run: |
#         /usr/local/lib/android/sdk/ndk/x.x.x/ndk-build
#         NDK_PROJECT_PATH=null
#         APP_BUILD_SCRIPT=/home/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/node_modules/react-native/ReactAndroid/src/main/jni/react/jni/Android.mk
#         NDK_APPLICATION_MK=/home/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/node_modules/react-native/ReactAndroid/src/main/jni/Application.mk

# E2E Release APK for Detox per VM image architecture for AVD
# --active-arch-only
# - M1: -PreactNativeArchitectures=arm64-v8a
# - Other: -PreactNativeArchitectures=x86_64

# Release AAB/APK with all 4 ABIs
# - 1 AAB/APK, 1 upload
# - Consider ccache without matrix
# - Parallelise each ABI via matrix
#   - Upload each ABI seperately
# - Consider sccache
#   - Bigger organisation/team
#   - Running more frequent builds
