# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Global envs
# env:
#   ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/x.x.x
#   ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/x.x.x

# TODO: Avoid brutally editing/setting ndk.dir in local.properties

jobs:
  build-android:

    runs-on: ubuntu-22.04

    # Local job envs

    steps:

    - uses: actions/checkout@v3

    # (Standalone toolchains obsolete)
    # Ubuntu 20.04: r21e, r22, r23b, Custom: r24+
    - name: Set up NDK r25 LTS
      uses: nttld/setup-ndk@v1.0.6
      with:
        ndk-version: r25

    # - name: Or manually set NDK X env vars
    #   run: |
    #     export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/x.x.x
    #     export ANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/x.x.x

    - name: Install all project dependencies
      run: yarn
      
    - name: Get and extract cmake-3.23.1-linux-x86_64.tar.gz to /usr/local/lib/android/sdk
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v3.23.1/cmake-3.23.1-linux-x86_64.tar.gz
        tar xzf cmake-3.23.1-linux-x86_64.tar.gz
        rm -rf cmake-3.23.1-linux-x86_64.tar.gz
        mkdir -p /usr/local/lib/android/sdk/cmake/3.22.1
        cp -rf cmake-3.23.1-linux-x86_64/* /usr/local/lib/android/sdk/cmake/3.22.1
        cd cmake-3.23.1-linux-x86_64
        ./bin/cmake --version

    - name: Build application Debug APK with Gradle
      uses: gradle/gradle-build-action@v2.2.5
      with:
        arguments: assembleDebug
        build-root-directory: android

    # Avoid release poisoned cache problems
    # Preserve hosted agent free disk space
    - name: Delete Android build pre-computed outputs
      uses: gradle/gradle-build-action@v2.2.5
      with:
        arguments: clean
        build-root-directory: android

    - name: Build application Release APK with Gradle
      uses: gradle/gradle-build-action@v2.2.5
      with:
        arguments: assembleRelease
        build-root-directory: android

#     - name: Build project Make-based (not CMake)
#       run: |
#         /usr/local/lib/android/sdk/ndk/x.x.x/ndk-build
#         NDK_PROJECT_PATH=null
#         APP_BUILD_SCRIPT=/home/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/node_modules/react-native/ReactAndroid/src/main/jni/react/jni/Android.mk
#         NDK_APPLICATION_MK=/home/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/node_modules/react-native/ReactAndroid/src/main/jni/Application.mk

# E2E Release APK for Detox per VM image architecture for AVD
# --active-arch-only
# - M1: -PreactNativeArchitectures=arm64-v8a
# - Other: -PreactNativeArchitectures=x86_64

# Release AAB/APK with all 4 ABIs
# - 1 AAB/APK, 1 upload
# - Consider ccache without matrix
# - Parallelise each ABI via matrix
#   - Upload each ABI seperately
# - Consider sccache
#   - Bigger organisation/team
#   - Running more frequent builds
